# roles/haproxy/tasks/sysctl.yml
---
- name: Set sysctl variables
  sysctl:
    name: "{{ item.key }}"
    sysctl_file: "{{ haproxy_sysctl_template_dest }}"
    value: "{{ item.value }}"
    sysctl_set: true
    reload: true
  with_dict: "{{ haproxy_sysctl_entries }}"
  tags: configure
  when:
    #- ansible_virtualization_type != 'docker'
    - haproxy_sysctl_managed
...
